
global batch size: 32
WARNING:tensorflow:From /opt/conda/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/liveness.py:83: Analyzer.lamba_check (from tensorflow.python.autograph.pyct.static_analysis.liveness) is deprecated and will be removed after 2023-09-23.
Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089
WARNING:tensorflow:From /opt/conda/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/liveness.py:83: Analyzer.lamba_check (from tensorflow.python.autograph.pyct.static_analysis.liveness) is deprecated and will be removed after 2023-09-23.
Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089
created dataset iterators
{'BN_momentum': 0.9, 'atac_mask_dropout': 0.1, 'bce_loss_scale': 0.95, 'decay_frac': 0.5, 'dropout_rate': 0.05, 'epsilon': 1e-08, 'filter_list_atac': [32, 64], 'filter_list_seq': [512, 640, 768, 896, 1024, 1152], 'final_output_length': 896, 'final_point_scale': 6, 'freeze_conv_layers': False, 'gradient_clip': 5, 'input_length': 196608, 'kernel_transformation': 'relu_kernel_transformation', 'learnable_PE': True, 'load_init': False, 'log_atac': True, 'lr_base1': 0.0002, 'lr_base2': 0.0002, 'num_heads': 8, 'num_random_features': 256, 'num_transformer_layers': 8, 'optimizer': 'adam', 'output_length': 1536, 'output_length_ATAC': 49152, 'output_res': 128, 'pointwise_dropout_rate': 0.1, 'random_mask_size': 512, 'rectify': True, 'seed': 24, 'sonnet_weights_bool': False, 'stable_variant': False, 'use_atac': True, 'use_seq': True, 'wd_1': 0.001, 'wd_2': 0.001, 'lr_base': 0.01, 'tpu': 'node-6', 'gcs_path': 'gs://picard-testing-176520/genformer_atac_pretrain/196k/genformer_atac_pretrain_globalacc_conv_rpgc_human', 'gcs_path_mm': None, 'gcs_path_rm': None, 'gcs_path_rat': None, 'gcs_path_holdout': 'gs://picard-testing-176520/genformer_atac_pretrain/196k/genformer_atac_pretrain_globalacc_conv_rpgc_val_holdout', 'num_epochs': 40, 'train_examples': 64, 'val_examples_ho': 64, 'batch_size': 4, 'warmup_frac': 0.025, 'patience': 50, 'min_delta': 5e-07, 'model_save_dir': 'gs://picard-testing-176520/genformer_atac_pretrain/models', 'model_save_basename': 'aformer', 'max_shift': 10, 'inits_type': 'enformer_conv', 'crop_size': 320, 'training_type': 'hg', 'output_heads': ['human'], 'train_steps': 2, 'val_steps_ho': 3, 'total_steps': 2}
initialized model
building model
/opt/conda/lib/python3.7/site-packages/keras/initializers/initializers_v2.py:121: UserWarning: The initializer RandomUniform is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  f"The initializer {self.__class__.__name__} is unseeded "
total params: tf.Tensor(125705810, shape=(), dtype=int32)
starting epoch_ 1
WARNING:tensorflow:Gradients do not exist for variables ['aformer/peaks_pool/dense_2/kernel:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
WARNING:tensorflow:Gradients do not exist for variables ['aformer/peaks_pool/dense_2/kernel:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
WARNING:tensorflow:Gradients do not exist for variables ['aformer/peaks_pool/dense_2/kernel:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
WARNING:tensorflow:Gradients do not exist for variables ['aformer/peaks_pool/dense_2/kernel:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
WARNING:tensorflow:Gradients do not exist for variables ['aformer/peaks_pool/dense_2/kernel:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
WARNING:tensorflow:Gradients do not exist for variables ['aformer/peaks_pool/dense_2/kernel:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
WARNING:tensorflow:Gradients do not exist for variables ['aformer/peaks_pool/dense_2/kernel:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
WARNING:tensorflow:Gradients do not exist for variables ['aformer/peaks_pool/dense_2/kernel:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
train_loss: 0.03459154
completed epoch 1
training duration(mins): 2.6100638707478843
val_loss: 0.026665142
val_loss_poisson: 0.013663414
val_loss_bce: 0.013001725
human_ATAC_pearsons: 0.06637307
human_ATAC_R2: -0.09628594
human_ATAC_PR: 0.003559535
human_ATAC_ROC: 0.46533626
completed epoch 1 validation
validation duration(mins): 0.6187076489130656
patience counter at: 0
starting epoch_ 2
WARNING:tensorflow:Gradients do not exist for variables ['aformer/peaks_pool/dense_2/kernel:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
WARNING:tensorflow:Gradients do not exist for variables ['aformer/peaks_pool/dense_2/kernel:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
WARNING:tensorflow:Gradients do not exist for variables ['aformer/peaks_pool/dense_2/kernel:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
WARNING:tensorflow:Gradients do not exist for variables ['aformer/peaks_pool/dense_2/kernel:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
[34m[1mwandb[39m[22m: Ctrl + C detected. Stopping sweep.
Exception ignored in: <module 'threading' from '/opt/conda/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt